enabled: true

# How often players' inventories will be checked for contraband.
minutes-between-checks: 5

messages:
#  pickup: "&c⚠ You picked up a disallowed item! This item has been removed from your inventory. ⚠"
  detect: "&c⚠ A disallowed item has been detected! Detected contraband has been removed from your inventory. ⚠"
  invalid: "&c✖ Invalid item. Please make sure you are providing a valid item. &c✖"
  commands:
    add:
      success: "&a✔ %item% has been marked as contraband. ✔"
    remove:
      success: "&c✔ %item% has been unmarked as contraband. ✔"
    usage: "&7[&c✖&7] /contraband <add/remove/toggle>"
    toggle:
      enable: "&7[&c✖&7] &aContraband will now be removed from players."
      disable: "&7[&c✖&7] &cContraband will no longer be removed from players."
