enabled: true
items:
  - BEDROCK
  - BARRIER
messages:
  pickup: "&c⚠ You picked up a disallowed item! This item has been removed from your inventory. ⚠"
  detect: "&c⚠ A disallowed item has been detected! This item has been removed from your inventory. ⚠"
  invalid: "&c✖ Invalid item. Please make sure you are providing a valid item. &c✖"
  commands:
    add:
      success: "&a✔ %item% has been marked as contraband. ✔"
    remove:
      success: "&c✔ %item% has been unmarked as contraband. ✔"
    usage: "&7[&c✖&7] /contraband <add/list/remove>"

