name: Contraband
version: '${project.version}'
main: xyz.twovb.contraband.Contraband
api-version: 1.16
author: 2vb
commands:
  contraband:
    description: Manage the server's contraband.
  test:
    description: debug command
permissions:
  contraband.manage:
    description: Allows players to manage contraband.
    default: false
  contraband.bypass:
    description: Bypass removal of contraband.
    default: false
